import { Order } from "@/types/order";

export const MOCK_ORDERS: Order[] = [
  {
    id: "1",
    orderNumber: "#78221",
    restaurant: "Burger King",
    restaurantLogo:
      "https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=200&h=200&fit=crop",
    location: "Dubai Marina",
    estimatedTime: "02:10 p.m.",
    status: "pending",
    statusBadge: "Almost Ready",
    actionType: "pickup",
    details: {
      customerName: "Mr. Ahmed R.",
      customerPhone: "+971 50 123 4567",
      items: ["Whopper Meal", "Chicken Royale", "Onion Rings", "2x Pepsi"],
      totalAmount: "AED 75.50",
    },
  },
  {
    id: "2",
    orderNumber: "#66109",
    restaurant: "Sushi House",
    restaurantLogo:
      "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=200&h=200&fit=crop",
    location: "Al Barsha 02",
    estimatedTime: "02:25 p.m.",
    status: "pending",
    statusBadge: "Preparing Order",
    actionType: "pickup",
    details: {
      customerName: "Ms. Rana M.",
      customerPhone: "+971 55 987 6543",
      items: ["California Roll", "Dragon Roll", "Miso Soup", "Edamame"],
      totalAmount: "AED 125.00",
    },
  },
  {
    id: "3",
    orderNumber: "#70988",
    restaurant: "Pizza Hut",
    restaurantLogo:
      "https://images.unsplash.com/photo-1513104890138-7c749659a593?w=200&h=200&fit=crop",
    location: "Jumeirah 1",
    estimatedTime: "01:35 p.m.",
    status: "pending",
    statusBadge: "Awaiting Confirmation",
    actionType: "pickup",
    details: {
      customerName: "Mr. Khalid S.",
      customerPhone: "+971 52 456 7890",
      items: ["Large Pepperoni Pizza", "Garlic Bread", "2x Coca Cola"],
      totalAmount: "AED 95.00",
    },
  },
  {
    id: "4",
    orderNumber: "#89453",
    restaurant: "Subway",
    restaurantLogo:
      "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=200&h=200&fit=crop",
    location: "Business Bay",
    estimatedTime: "01:50 p.m.",
    status: "assigned",
    statusBadge: "In Transit",
    actionType: "delivery",
    pickupConfirmed: true,
    details: {
      customerName: "Ms. Fatima K.",
      customerPhone: "+971 56 234 5678",
      items: ["Italian BMT Footlong", 'Veggie Delite 6"', "Cookies"],
      totalAmount: "AED 55.00",
    },
  },
  {
    id: "5",
    orderNumber: "#92134",
    restaurant: "McDonald's",
    restaurantLogo:
      "https://images.unsplash.com/photo-1619454016518-697bc231e7cb?w=200&h=200&fit=crop",
    location: "Al Barsha South",
    estimatedTime: "02:30 p.m.",
    status: "assigned",
    statusBadge: "In Transit",
    actionType: "delivery",
    pickupConfirmed: true,
    details: {
      customerName: "Mr. Omar M.",
      customerPhone: "+971 50 876 5432",
      items: ["Big Mac Meal", "McChicken", "Large Fries", "McFlurry"],
      totalAmount: "AED 67.50",
    },
  },
  {
    id: "9",
    orderNumber: "#44567",
    restaurant: "Texas Chicken",
    restaurantLogo:
      "https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?w=200&h=200&fit=crop",
    location: "City Walk",
    estimatedTime: "02:15 p.m.",
    status: "assigned",
    statusBadge: "Awaiting Pickup",
    actionType: "pickup",
    pickupConfirmed: false,
    details: {
      customerName: "Ms. Layla H.",
      customerPhone: "+971 55 444 5566",
      items: ["Spicy Wings Box", "Tenders Meal", "Fries", "2x Pepsi"],
      totalAmount: "AED 82.00",
    },
  },
  {
    id: "10",
    orderNumber: "#33890",
    restaurant: "Olive Garden",
    restaurantLogo:
      "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=200&h=200&fit=crop",
    location: "Dubai Mall",
    estimatedTime: "02:40 p.m.",
    status: "assigned",
    statusBadge: "Awaiting Pickup",
    actionType: "pickup",
    pickupConfirmed: false,
    details: {
      customerName: "Mr. Hassan A.",
      customerPhone: "+971 52 777 8899",
      items: [
        "Fettuccine Alfredo",
        "Chicken Parmigiana",
        "Garlic Breadsticks",
        "Tiramisu",
      ],
      totalAmount: "AED 145.00",
    },
  },
  {
    id: "6",
    orderNumber: "#55432",
    restaurant: "Little Caesars",
    restaurantLogo:
      "https://images.unsplash.com/photo-1534308983664-4f78cd6fb8e5?w=200&h=200&fit=crop",
    location: "Muhaisnah",
    estimatedTime: "12:45 p.m.",
    status: "completed",
    statusBadge: "Completed",
    actionType: "delivery",
    details: {
      customerName: "Mr. Khalid A.",
      customerPhone: "+971 55 321 9876",
      items: ["Large Pepperoni Pizza", "Crazy Bread", "2x Pepsi"],
      totalAmount: "AED 78.00",
      deliveryTime: "12:45 p.m.",
    },
  },
  {
    id: "7",
    orderNumber: "#49987",
    restaurant: "KFC",
    restaurantLogo:
      "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=200&h=200&fit=crop",
    location: "JLT Cluster D",
    estimatedTime: "11:20 a.m.",
    status: "completed",
    statusBadge: "Completed",
    actionType: "delivery",
    details: {
      customerName: "Ms. Rana M.",
      customerPhone: "+971 54 567 8901",
      items: ["Zinger Box", "Popcorn Chicken", "Coleslaw", "Pepsi"],
      totalAmount: "AED 62.50",
      deliveryTime: "11:20 a.m.",
    },
  },
  {
    id: "8",
    orderNumber: "#61223",
    restaurant: "Chili Chin",
    restaurantLogo:
      "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=200&h=200&fit=crop",
    location: "Al Barsha South",
    estimatedTime: "10:15 a.m.",
    status: "completed",
    statusBadge: "Completed",
    actionType: "delivery",
    details: {
      customerName: "Mr. Omar K.",
      customerPhone: "+971 52 789 0123",
      items: [
        "Kung Pao Chicken",
        "Fried Rice",
        "Spring Rolls",
        "Sweet & Sour Soup",
      ],
      totalAmount: "AED 98.00",
      deliveryTime: "01:28 p.m.",
    },
  },
];
